<!DOCTYPE html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="author" content="Mina Kim" />
    
    <link rel="shortcut icon" type="image/x-icon" href="../../img/favicon.ico">
    <title>Project 2: Modeling, Testing, and Predicting</title>
    <meta name="generator" content="Hugo 0.83.1" />
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../css/main.css" />
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" />
    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:200,400,200bold,400old" />
    
    <!--[if lt IE 9]>
			<script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
			<script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
		<![endif]-->

    
  </head>

  <body>
    <div id="wrap">
      
      <nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="../../"><i class="fa fa-home"></i></a>
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>
    <div class="navbar-collapse collapse" id="navbar">
      <ul class="nav navbar-nav navbar-right">
      
        
        <li><a href="../../post/">BLOG</a></li>
        
        <li><a href="../../projects/">PROJECTS</a></li>
        
        <li><a href="../../resume/">RESUME</a></li>
        
      
      </ul>
    </div>
  </div>
</nav>

      <div class="container">
        <div class="blog-post">
          <h3>
            <strong><a href="../../project/project2/">Project 2: Modeling, Testing, and Predicting</a></strong>
          </h3>
        </div>
 
<div class="blog-title">
          <h4>
         January 1, 0001 
            &nbsp;&nbsp;
            
          </h4>
        </div>

        <div class="panel panel-default">
          <div class="panel-body">
            <div class="blogpost">
              


<div id="mina-kim-mlk2589" class="section level2">
<h2>Mina Kim MLK2589</h2>
</div>
<div id="modeling-testing-and-predicting" class="section level2">
<h2>Modeling, Testing, and Predicting</h2>
<p>This project analyzes the “Stroke prediction dataset” provided by data scientist Federico Soriano. The dataset compiles 10 clinical features that may be associated with stroke for 5110 anonymized patients. As stroke is the 2nd leading cause of death worldwide and accounts for about 11% of deaths, analyzing this dataset for any possible associations could help improve clinical outcomes for this medical emergency. Since I’m a neuroscience major, finding how this neurological disease is affected by other clinical factors is also inherently interesting.</p>
<p>The dataset has 5110 observations, each observation being a patient. There are 12 variables, one for the anonymized patient ID, and one a binary variable for a stroke event occuring. The other 10 variables are: gender (Male, Female, Other), age (years), hypertension (binary), heart_disease (binary), ever_married (Yes, No), work_type (children, govt_job, never_worked, private, self-employed), residence_type (rural, urban), avg_glucose_level, bmi, and smoking_status (formerly smoked, never smoked, smokes, unknown).</p>
<pre class="r"><code>library(&quot;tidyverse&quot;)
library(dplyr)
library(rstatix)
library(modelr)
library(tidyverse)
library(gridExtra)
library(sandwich)
library(lmtest)

stroke &lt;- read.csv(&quot;~/SDS_348/healthcare-dataset-stroke-data.csv&quot;, na.strings = c(&quot;N/A&quot;))
stroke &lt;- stroke %&gt;% na.omit
head(stroke)</code></pre>
<pre><code>## id gender age hypertension heart_disease ever_married
work_type Residence_type
## 1 9046 Male 67 0 1 Yes Private Urban
## 3 31112 Male 80 0 1 Yes Private Rural
## 4 60182 Female 49 0 0 Yes Private Urban
## 5 1665 Female 79 1 0 Yes Self-employed Rural
## 6 56669 Male 81 0 0 Yes Private Urban
## 7 53882 Male 74 1 1 Yes Private Rural
## avg_glucose_level bmi smoking_status stroke
## 1 228.69 36.6 formerly smoked 1
## 3 105.92 32.5 never smoked 1
## 4 171.23 34.4 smokes 1
## 5 174.12 24.0 never smoked 1
## 6 186.21 29.0 formerly smoked 1
## 7 70.09 27.4 never smoked 1</code></pre>
</div>
<div id="manova-testing" class="section level2">
<h2>MANOVA testing</h2>
<pre class="r"><code>group &lt;- stroke$Residence_type
DVs &lt;- stroke %&gt;% select(age,hypertension,heart_disease,avg_glucose_level,bmi,stroke)

sapply(split(DVs,group), mshapiro_test)</code></pre>
<pre><code>##           Rural        Urban       
## statistic 0.9118631    0.941912    
## p.value   2.403272e-35 3.231558e-30</code></pre>
<pre class="r"><code>man &lt;- manova(cbind(age,hypertension,heart_disease,avg_glucose_level,bmi,stroke)~Residence_type, data=stroke)
summary(man)</code></pre>
<pre><code>## Df Pillai approx F num Df den Df Pr(&gt;F)
## Residence_type 1 0.00028994 0.23695 6 4902 0.9645
## Residuals 4907</code></pre>
<pre class="r"><code># Type I error
1-(0.95)^31</code></pre>
<pre><code>## [1] 0.7960932</code></pre>
<p>The MANOVA test didn’t yield a significant enough mean difference in my numeric variables (age, hypertension, heart disease, average glucose levels, bmi, and stroke) across levels of residence types. However, if the summary did show significance, I’d have my 1 MANOVA test, 6 univariate ANOVA tests, and 24 unique t tests for 31 tests total. The probability of a type 1 error occurring was calculated as 1-(0.95)^31 = 79.6%, and if I ran ANOVA, bonferroni would correct alpha to 0.05. MANOVA assumptions were not met.</p>
</div>
<div id="randomization-tests" class="section level2">
<h2>Randomization tests</h2>
<pre class="r"><code>stroke%&gt;%group_by(stroke)%&gt;%
  summarise(means=mean(bmi))%&gt;%summarise(`mean_diff`=diff(means))</code></pre>
<pre><code>## # A tibble: 1 x 1
##   mean_diff
##       &lt;dbl&gt;
## 1      1.65</code></pre>
<pre class="r"><code>rand_dist&lt;-vector() 

for(i in 1:5000){
new&lt;-data.frame(bmi=sample(stroke$bmi),stroke=stroke$stroke) 
rand_dist[i]&lt;-mean(new[new$stroke==&quot;1&quot;,]$bmi)-   
              mean(new[new$stroke==&quot;0&quot;,]$bmi)}

{hist(rand_dist,main=&quot;&quot;,ylab=&quot;&quot;); abline(v = c(-1.65, 1.65),col=&quot;red&quot;)}</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-3-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>mean(rand_dist&gt;1.65 | rand_dist&lt; -1.65)</code></pre>
<pre><code>## [1] 0.0036</code></pre>
<p>I randomized my data to test for a mean difference in BMIs between populations that have strokes and populations that don’t. My null hypothesis states that there is no mean difference in BMIs between patients that do and don’t have stroke, while my alternative hypothesis states there is a mean difference in BMIs between stroke and non-stroke patients. To test the mean difference, I found the mean difference test statistic is 1.65, and randomized the data. I plotted the randomized distribution and the statistic with red lines, and found the p value to be 0.0048. Because the p value is less than alpha = 0.05, I reject the null hypothesis and state there is a mean difference in BMIs across stroke and non-stroke populations.</p>
</div>
<div id="linear-regression" class="section level2">
<h2>Linear Regression</h2>
<pre class="r"><code>stroke$avg_glucose_level_c &lt;- stroke$avg_glucose_level - mean(stroke$avg_glucose_level)
stroke$age_c &lt;- stroke$age - mean(stroke$age)
fit&lt;-lm(avg_glucose_level_c ~ smoking_status*age_c, data=stroke)
summary(fit)</code></pre>
<pre><code>##
## Call:
## lm(formula = avg_glucose_level_c ~ smoking_status *
age_c, data = stroke)
##
## Residuals:
## Min 1Q Median 3Q Max
## -73.40 -28.30 -11.70 13.47 163.92
##
## Coefficients:
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.57418 1.80386 -0.873 0.3829
## smoking_statusnever smoked 1.44437 2.07080 0.697 0.4855
## smoking_statussmokes 0.43761 2.43524 0.180 0.8574
## smoking_statusUnknown -1.80142 2.20697 -0.816 0.4144
## age_c 0.73385 0.08455 8.680 &lt; 2e-16 ***
## smoking_statusnever smoked:age_c -0.18974 0.09862 -1.924
0.0544 .
## smoking_statussmokes:age_c -0.17644 0.12906 -1.367
0.1717
## smoking_statusUnknown:age_c -0.46475 0.09595 -4.844
1.31e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1
##
## Residual standard error: 43.05 on 4901 degrees of
freedom
## Multiple R-squared: 0.06214, Adjusted R-squared: 0.0608
## F-statistic: 46.39 on 7 and 4901 DF, p-value: &lt; 2.2e-16</code></pre>
<pre class="r"><code>ggplot(stroke, aes(x=age_c, y=avg_glucose_level_c,group=smoking_status))+geom_point()+
  geom_smooth(method=&quot;lm&quot;,se=F,fullrange=T,aes(color=smoking_status))</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>resids&lt;-fit$residuals
par(mfrow = c(1, 2)); hist(resids); qqnorm(resids); qqline(resids, col = &#39;red&#39;)</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-4-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>coeftest(fit, vcov = vcovHC(fit))</code></pre>
<pre><code>##
## t test of coefficients:
##
## Estimate Std. Error t value Pr(&gt;|t|)
## (Intercept) -1.574178 1.600759 -0.9834 0.32546
## smoking_statusnever smoked 1.444367 1.871110 0.7719
0.44019
## smoking_statussmokes 0.437610 2.223147 0.1968 0.84396
## smoking_statusUnknown -1.801422 2.050581 -0.8785 0.37972
## age_c 0.733847 0.089683 8.1827 3.505e-16 ***
## smoking_statusnever smoked:age_c -0.189741 0.106017
-1.7897 0.07356 .
## smoking_statussmokes:age_c -0.176438 0.140797 -1.2531
0.21022
## smoking_statusUnknown:age_c -0.464746 0.099720 -4.6605
3.238e-06 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<p>The mean predicted average glucose levels are -1.57 for former smokers and mean centered age, but was not found as significant. For each of the significant estimates, which is age and unknown smoking status accounting for age, the estimate provides the average increase in those factors with every 1 increase in average glucose levels. Around 6.1% of the proportion of the variation is explained by the model. Recomputing with robust standard error doesn’t change any significant results. Judging by the plot, the fit violates homoskedasticity and the residuals show normality and linearity are violated.</p>
</div>
<div id="bootstrapped-linear-regression" class="section level2">
<h2>Bootstrapped Linear Regression</h2>
<pre class="r"><code>library(sandwich)
library(lmtest)
boot_dat&lt;-stroke[sample(nrow(stroke),replace=TRUE),]


samp_distn&lt;-replicate(5000, {
  boot_dat&lt;-boot_dat&lt;-stroke[sample(nrow(stroke),replace=TRUE),]
  fit_2 &lt;- lm(avg_glucose_level_c ~ smoking_status*age_c, data=boot_dat)
  coef(fit_2)
})

## Estimated SEs
samp_distn%&gt;%t%&gt;%as.data.frame%&gt;%summarize_all(sd)</code></pre>
<pre><code>## (Intercept) smoking_statusnever smoked
smoking_statussmokes smoking_statusUnknown age_c
## 1 1.595478 1.860365 2.240581 2.082274 0.0893183
## smoking_statusnever smoked:age_c
smoking_statussmokes:age_c smoking_statusUnknown:age_c
## 1 0.106132 0.1408576 0.09911148</code></pre>
<p>Bootstrapping didn’t change the estimated SEs much, any variation can be attributed to the non-infinite running of samples.</p>
</div>
<div id="logistic-regression" class="section level2">
<h2>Logistic Regression</h2>
<pre class="r"><code>fit_3&lt;-glm(stroke~bmi + age, data=stroke, family=&quot;binomial&quot;)
coeftest(fit_3)</code></pre>
<pre><code>##
## z test of coefficients:
##
## Estimate Std. Error z value Pr(&gt;|z|)
## (Intercept) -7.9435199 0.5429719 -14.6297 &lt;2e-16 ***
## bmi 0.0162490 0.0111226 1.4609 0.144
## age 0.0760913 0.0054693 13.9125 &lt;2e-16 ***
## ---
## Signif. codes: 0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1
&#39; &#39; 1</code></pre>
<pre class="r"><code>exp(coef(fit_3))</code></pre>
<pre><code>##  (Intercept)          bmi          age 
## 0.0003549549 1.0163817482 1.0790610390</code></pre>
<pre class="r"><code>stroke &lt;- stroke%&gt;%mutate(prob=predict(fit_3, type= &quot;response&quot;), prediction=ifelse(prob&gt;.5,1,0))
table(predict=as.numeric(stroke$prob&gt;.5),truth=stroke$stroke)%&gt;%addmargins</code></pre>
<pre><code>##        truth
## predict    0    1  Sum
##     0   4700  209 4909
##     Sum 4700  209 4909</code></pre>
<pre class="r"><code>#accuracy
4700/4909</code></pre>
<pre><code>## [1] 0.9574251</code></pre>
<pre class="r"><code>#TNR
4700/4700</code></pre>
<pre><code>## [1] 1</code></pre>
<pre class="r"><code>stroke$logit &lt;- predict(fit_3, type=&quot;link&quot;)
stroke%&gt;%ggplot()+geom_density(aes(logit,color=stroke,fill=stroke), alpha=.4)+
  theme(legend.position=c(.85,.85))+geom_vline(xintercept=0)+xlab(&quot;logit (log-odds)&quot;)+
  geom_rug(aes(logit,color=stroke))</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-6-1.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>library(plotROC)

classify&lt;-stroke%&gt;%transmute(prob,prediction,truth=stroke)
ROCplot&lt;-ggplot(classify)+ geom_roc(aes(d=truth,m=prob), n.cuts=0)
ROCplot</code></pre>
<p><img src="../../project/Project2_files/figure-html/unnamed-chunk-6-2.png" width="768" style="display: block; margin: auto;" /></p>
<pre class="r"><code>calc_auc(ROCplot)</code></pre>
<pre><code>##   PANEL group       AUC
## 1     1    -1 0.8365881</code></pre>
<p>I ran a logistic regression on the variables BMI and age on stroke occurence. For 0 BMI and 0 age, stroke occurence is at -7.94 which was found to be statistically significant. Additionally, age was also found to be a significant variable as 0 bmi and average age results in a 0.076 occurence of stroke. When reporting a confusion matrix, there weren’t any predicted values of 1, so only the accuracy and TNR were calculated, although those values were pretty in line with the actual results with good accuracy ratings. AUC was calculated as 0.8365, which is pretty good.</p>
<pre class="r"><code>stroke &lt;- stroke %&gt;% mutate(y = ifelse(stroke == &quot;1&quot;, 1,0))
fit_all &lt;-glm(stroke~., data=stroke, family = &quot;binomial&quot;)
prob2 &lt;- predict(fit_all)
coef(fit_all)</code></pre>
<pre><code>## (Intercept) id genderMale
## -2.656607e+01 4.352717e-18 -8.667766e-14
## genderOther age hypertension
## -3.109232e-14 -1.908589e-14 7.700918e-13
## heart_disease ever_marriedYes work_typeGovt_job
## -1.395375e-12 9.096435e-14 6.353126e-13
## work_typeNever_worked work_typePrivate
work_typeSelf-employed
## -5.106722e-15 4.542091e-13 5.874065e-13
## Residence_typeUrban avg_glucose_level bmi
## -1.058582e-13 -1.638580e-15 -1.239259e-14
## smoking_statusnever smoked smoking_statussmokes
smoking_statusUnknown
## 3.923537e-13 4.246572e-13 3.758780e-13
## avg_glucose_level_c age_c prob
## NA NA 9.754768e-12
## prediction logit y
## NA NA 5.313214e+01</code></pre>
<pre class="r"><code>exp(coef(fit_all))</code></pre>
<pre><code>## (Intercept) id genderMale
## 2.900701e-12 1.000000e+00 1.000000e+00
## genderOther age hypertension
## 1.000000e+00 1.000000e+00 1.000000e+00
## heart_disease ever_marriedYes work_typeGovt_job
## 1.000000e+00 1.000000e+00 1.000000e+00
## work_typeNever_worked work_typePrivate
work_typeSelf-employed
## 1.000000e+00 1.000000e+00 1.000000e+00
## Residence_typeUrban avg_glucose_level bmi
## 1.000000e+00 1.000000e+00 1.000000e+00
## smoking_statusnever smoked smoking_statussmokes
smoking_statusUnknown
## 1.000000e+00 1.000000e+00 1.000000e+00
## avg_glucose_level_c age_c prob
## NA NA 1.000000e+00
## prediction logit y
## NA NA 1.188486e+23</code></pre>
<pre class="r"><code>class_diag &lt;- function(probs,truth){
  #CONFUSION MATRIX: CALCULATE ACCURACY, TPR, TNR, PPV
  tab&lt;-table(factor(probs&gt;.5,levels=c(&quot;FALSE&quot;,&quot;TRUE&quot;)),truth)
  acc=sum(diag(tab))/sum(tab)
  sens=tab[2,2]/colSums(tab)[2]
  spec=tab[1,1]/colSums(tab)[1]
  ppv=tab[2,2]/rowSums(tab)[2]
  f1=2*(sens*ppv)/(sens+ppv)
  
  if(is.numeric(truth)==FALSE &amp; is.logical(truth)==FALSE) truth&lt;-as.numeric(truth)-1
  
  #CALCULATE EXACT AUC
  ord&lt;-order(probs, decreasing=TRUE)
  probs &lt;- probs[ord]; truth &lt;- truth[ord]
  
  TPR=cumsum(truth)/max(1,sum(truth)) 
  FPR=cumsum(!truth)/max(1,sum(!truth))
  
  dup&lt;-c(probs[-1]&gt;=probs[-length(probs)], FALSE)
  TPR&lt;-c(0,TPR[!dup],1); FPR&lt;-c(0,FPR[!dup],1)
  n &lt;- length(TPR)
  auc&lt;- sum( ((TPR[-1]+TPR[-n])/2) * (FPR[-1]-FPR[-n]) )
  
  data.frame(acc,sens,spec,ppv,f1,auc)
}

truth = stroke$y
class_diag(prob2, truth)</code></pre>
<pre><code>##   acc sens spec ppv f1 auc
## 1   1    1    1   1  1   1</code></pre>
<pre class="r"><code>#confusion matrix
table(prediction=as.numeric(prob2&gt;.5), truth)%&gt;% addmargins()</code></pre>
<pre><code>##           truth
## prediction    0    1  Sum
##        0   4700    0 4700
##        1      0  209  209
##        Sum 4700  209 4909</code></pre>
<pre class="r"><code>set.seed(1234)
k=10

data_CV&lt;-stroke[sample(nrow(stroke)),] 
folds&lt;-cut(seq(1:nrow(stroke)),breaks=k,labels=F) 

diags&lt;-NULL
for(i in 1:k){
  train&lt;-data_CV[folds!=i,]
  test&lt;-data_CV[folds==i,]
  
  truth1&lt;-test$y
  
  fitCV1&lt;- glm(y~.,data=train[,!colnames(train) %in% c(&quot;gender&quot;)],family=&quot;binomial&quot;)
  
  probs_CV&lt;-predict(fitCV1,newdata = test,type=&quot;response&quot;)
  
  diags&lt;-rbind(diags,class_diag(probs_CV,truth1))
}


summarize_all(diags,mean) </code></pre>
<pre><code>##   acc sens spec ppv f1 auc
## 1   1    1    1   1  1   1</code></pre>
<pre class="r"><code>library(glmnet)
set.seed(1234)

x&lt;-model.matrix(y ~ ., data=stroke)
y&lt;-data.matrix(stroke$y)

cv&lt;-cv.glmnet(x,y, family = &quot;binomial&quot;)
lasso&lt;-glmnet(x,y,family=&quot;binomial&quot;,lambda=cv$lambda.1se)
coef(lasso)</code></pre>
<pre><code>## 25 x 1 sparse Matrix of class &quot;dgCMatrix&quot;
##                            s0
## (Intercept)                 .
## (Intercept)                 0
## id                          .
## genderMale                  .
## genderOther                 .
## age                         .
## hypertension                .
## heart_disease               .
## ever_marriedYes             .
## work_typeGovt_job           .
## work_typeNever_worked       .
## work_typePrivate            .
## work_typeSelf-employed      .
## Residence_typeUrban         .
## avg_glucose_level           .
## bmi                         .
## smoking_statusnever smoked  .
## smoking_statussmokes        .
## smoking_statusUnknown       .
## stroke                      .
## avg_glucose_level_c         .
## age_c                       .
## prob                        .
## prediction                  .
## logit                       .</code></pre>
<pre class="r"><code>set.seed(1234)
k=10 #choose number of folds
stroke_4&lt;- stroke %&gt;% sample_frac
folds &lt;- ntile(1:nrow(stroke_4),n=10)

diags&lt;-NULL 
for(i in 1:k){
  train&lt;-stroke_4[folds!=i,] 
  test&lt;-stroke_4[folds==i,]
  truth &lt;- test$y
  fit5&lt;-glm(y~id, data=train, family=&quot;binomial&quot;) 
  probs5 &lt;- predict(fit5, newdata=test, type=&quot;response&quot;)
  yhat&lt;-predict(fit5,newdata=test)
  diags&lt;-rbind(diags,class_diag(probs5,truth))
}
diags%&gt;%summarize_all(mean)</code></pre>
<pre><code>##         acc sens spec ppv  f1      auc
## 1 0.9574272    0    1 NaN NaN 0.462435</code></pre>
<p>After fitting the model for all variables, I had an AUC of 1 which is very high. After CV, this value stayed the same, indicating that there isn’t evidence of overfitting. Running lasso yielded only the ID variable that was selected for out of sample AUC, which after running AUC, yielded an AUC of 0.4624 which is very poor.</p>
<p>…</p>
</div>

            
        <hr>         <div class="related-posts">
                <h5>Related Posts</h5>
                
              </div> 
            </div>
          </div>

   <hr>  <div class="disqus">
  <div id="disqus_thread"></div>
  <script type="text/javascript">

    (function() {
      
      
      if (window.location.hostname == "localhost")
        return;

      var disqus_shortname = '';
      var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
      dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
      (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
    })();
  </script>
  <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
  <a href="http://disqus.com/" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
</div> 
        </div>
      </div>
    </div>

    
    <footer>
  <div id="footer">
    <div class="container">
      <p class="text-muted">&copy; All rights reserved. Powered by <a href="https://gohugo.io/">Hugo</a> and
      <a href="http://www.github.com/nurlansu/hugo-sustain/">sustain</a> with ♥</p>
    </div>
  </div>
</footer>
<div class="footer"></div>


<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="../../js/docs.min.js"></script>
<script src="../../js/main.js"></script>

<script src="../../js/ie10-viewport-bug-workaround.js"></script>


    
  </body>
</html>
